### PR TITLE
Throw exception on AEAD decryption failure

### LINKED ISSUE #89: AEAD.Lazy does not throw exception for failed authentication
AEAD.Lazy silently decrypts a ciphertext which fails authentication. For instance, calling decrypt for XChaCha20-Poly1305 ignores the return value of `cryptoAeadXChaCha20Poly1305IetfDecrypt()`

https://github.com/terl/lazysodium-java/blob/ea27165505717d26f8249bb425e5061efbd43270/src/main/java/com/goterl/lazycode/lazysodium/LazySodium.java#L2412

IMHO, the decrypt method should throw an exception in order to alert the user of the library that the decryption was unsuccessful.

### PR DESCRIPTION
**Pull request by gnarula**
~Adds `AEADAuthenticationException` which is thrown if any AEAD decryption fails.~

Throws `javax.crypto.AEADBadTagException` in case of AEAD decryption failure.

This is a backwards incompatible change to the API and might require a major version bump.

Fixes #89

### CODE REVIEW

File: src/main/java/com/goterl/lazycode/lazysodium/LazySodium.java [hunk 1]
```diff
@@ -16,6 +16,7 @@
 import com.sun.jna.ptr.IntByReference;
 import com.sun.jna.ptr.PointerByReference;
 
+import javax.crypto.AEADBadTagException;
```
Comment (gurpreet-) [inline src/main/java/com/goterl/lazycode/lazysodium/LazySodium.java:19]: As Lazysodium is available across Java and Android, I'd really rather not include a new package if possible.

File: src/main/java/com/goterl/lazycode/lazysodium/LazySodium.java [hunk 2]
```diff
@@ -2368,20 +2369,20 @@ public String encrypt(String m, String additionalData, byte[] nSec, byte[] nPub,
...
+    public String decrypt(String cipher, String additionalData, byte[] nSec, byte[] nPub, Key k, AEAD.Method method) throws AEADBadTagException {
         byte[] cipherBytes = messageEncoder.decode(cipher);
         byte[] additionalDataBytes = additionalData == null ? new byte[0] : bytes(additionalData);
         long additionalBytesLen = additionalData == null ? 0L : additionalDataBytes.length;
         byte[] keyBytes = k.getAsBytes();
 
         if (method.equals(AEAD.Method.CHACHA20_POLY1305)) {
             byte[] messageBytes = new byte[cipherBytes.length - AEAD.CHACHA20POLY1305_ABYTES];
-            cryptoAeadChaCha20Poly1305Decrypt(
+            if(!cryptoAeadChaCha20Poly1305Decrypt(
```
Comment (gurpreet-) [inline src/main/java/com/goterl/lazycode/lazysodium/LazySodium.java:2385]:
```suggestion
            if (!cryptoAeadChaCha20Poly1305Decrypt(
```

**Comment by gurpreet-** [comment]
Thanks so much for the PR!

The only problem I have with it is addition of a new package 😕 I see you also added a custom exception at one point, may I ask why you used `javax.crypto.AEADBadTagException` rather than `AEADAuthenticationException`? 🙂

**Comment by gnarula** [comment]
> The only problem I have with it is addition of a new package 😕 I see you also added a custom exception at one point, may I ask why you used `javax.crypto.AEADBadTagException` rather than `AEADAuthenticationException`? 🙂

I thought it's better to use an existing Exception in the Java Cryptography Extension API which denotes the same cause.

I reckon javax.crypto.AEADBadTagException is available in JDK >= 1.7 and Android API >= 19 so there aren't any external dependencies being added. Does the project support JDK/Android targets below this? I'd be happy to change it however you see fit.

**Comment by gurpreet-** [comment]
OK you have convinced me. It's better to reuse than reinvent the wheel. Let's keep it using `javax.crypto.AEADBadTagException` 👍

File: src/test/java/com/goterl/lazycode/lazysodium/AEADTest.java [hunk 3]
```diff
@@ -122,8 +211,22 @@ public void encryptAES() {
         }
     }
 
+    @Test(expected = AEADBadTagException.class)
+    public void encryptAESMalformedCipher() throws AEADBadTagException {
+        if (lazySodium.cryptoAeadAES256GCMIsAvailable()) {
```
Comment (gurpreet-) [inline src/test/java/com/goterl/lazycode/lazysodium/AEADTest.java:216]: Hi, because of this if statement, wouldn't this fail if `cryptoAeadAES256GCMIsAvailable` is false because it expects an exception (`@Test(expected = AEADBadTagException.class)`) all the time?

File: src/test/java/com/goterl/lazycode/lazysodium/BaseTest.java [hunk 4]
```diff
@@ -8,16 +8,20 @@
...
 
 public class BaseTest {
 
     public static LazySodiumJava lazySodium;
+    public static MessageEncoder encoder;
 
     @Before
     public void doBeforeEverything() {
         lazySodium = new LazySodiumJava(new SodiumJava(LibraryLoader.Mode.BUNDLED_ONLY));
+        encoder = new HexMessageEncoder();
```
Comment (gurpreet-) [inline src/test/java/com/goterl/lazycode/lazysodium/BaseTest.java:24]: This can probably be moved to `AEADTest` rather than be added to the `BaseTest` class.

**Comment by gurpreet-** [comment]
Hey I'll merge but then pickup the changes myself 👍
